# Generated by Django 4.2.3 on 2023-07-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product_categari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_image')),
                ('model', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_master')),
            ],
        ),
    ]
